#pragma once

constexpr unsigned int SMOOTHIE_MAX_FRAMES_IN_FLIGHT = 3;
constexpr unsigned int SMOOTHIE_IMAGE_MAX_LOD_MODEL_IMAGE = 10;

constexpr inline char* SMOOTHIE_MODEL_DESCRIPTOR_UBO_IDENTIFIER = "ModelData";
constexpr inline char* SMOOTHIE_MODEL_DESCRIPTOR_STORAGE_IDENTIFIER = "A";


enum class ShaderPipelineType
{
	UNDEFINED = 0,
	RASTERIZATION = 1,
	COMPUTE = 2,
	RAYTRACING = 3
};

enum ModelDescriptorDataType
{
	MODEL_DESCRIPTOR_DATA_TYPE_NO_TYPE = 0,

	MODEL_DESCRIPTOR_DATA_TYPE_BYTE = 0x1400,
	MODEL_DESCRIPTOR_DATA_TYPE_UNSIGNED_BYTE = 0x1401,

	MODEL_DESCRIPTOR_DATA_TYPE_SHORT = 0x1402,
	MODEL_DESCRIPTOR_DATA_TYPE_UNSIGNED_SHORT = 0x1403,

	MODEL_DESCRIPTOR_DATA_TYPE_BOOL = 0x8B56,
	MODEL_DESCRIPTOR_DATA_TYPE_BOOL_VEC2 = 0x8B57,
	MODEL_DESCRIPTOR_DATA_TYPE_BOOL_VEC3 = 0x8B58,
	MODEL_DESCRIPTOR_DATA_TYPE_BOOL_VEC4 = 0x8B59,

	MODEL_DESCRIPTOR_DATA_TYPE_FLOAT = 0x1406,
	MODEL_DESCRIPTOR_DATA_TYPE_FLOAT_VEC2 = 0x8B50,
	MODEL_DESCRIPTOR_DATA_TYPE_FLOAT_VEC3 = 0x8B51,
	MODEL_DESCRIPTOR_DATA_TYPE_FLOAT_VEC4 = 0x8B52,

	MODEL_DESCRIPTOR_DATA_TYPE_DOUBLE = 0x140A,
	MODEL_DESCRIPTOR_DATA_TYPE_DOUBLE_VEC2 = 0x8FFC,
	MODEL_DESCRIPTOR_DATA_TYPE_DOUBLE_VEC3 = 0x8FFD,
	MODEL_DESCRIPTOR_DATA_TYPE_DOUBLE_VEC4 = 0x8FFE,

	MODEL_DESCRIPTOR_DATA_TYPE_INT = 0x1404,
	MODEL_DESCRIPTOR_DATA_TYPE_INT_VEC2 = 0x8B53,
	MODEL_DESCRIPTOR_DATA_TYPE_INT_VEC3 = 0x8B54,
	MODEL_DESCRIPTOR_DATA_TYPE_INT_VEC4 = 0x8B55,

	MODEL_DESCRIPTOR_DATA_TYPE_UNSIGNED_INT = 0x1405,
	MODEL_DESCRIPTOR_DATA_TYPE_UNSIGNED_INT_VEC2 = 0x8DC6,
	MODEL_DESCRIPTOR_DATA_TYPE_UNSIGNED_INT_VEC3 = 0x8DC7,
	MODEL_DESCRIPTOR_DATA_TYPE_UNSIGNED_INT_VEC4 = 0x8DC8,
	
	MODEL_DESCRIPTOR_DATA_TYPE_FLOAT_MAT2 = 0x8B5A,
	MODEL_DESCRIPTOR_DATA_TYPE_FLOAT_MAT3 = 0x8B5B,
	MODEL_DESCRIPTOR_DATA_TYPE_FLOAT_MAT4 = 0x8B5C,

	MODEL_DESCRIPTOR_SAMPLER_1D = 0x8B5D,
	MODEL_DESCRIPTOR_SAMPLER_2D = 0x8B5E,
	MODEL_DESCRIPTOR_SAMPLER_3D = 0x8B5F,
	MODEL_DESCRIPTOR_SAMPLER_CUBE = 0x8B60,
	
	MODEL_DESCRIPTOR_IMAGE_1D = 0x904C,
	MODEL_DESCRIPTOR_IMAGE_2D = 0x904D,
	MODEL_DESCRIPTOR_IMAGE_3D = 0x904E,
	MODEL_DESCRIPTOR_IMAGE_CUBE = 0x9050,

	MODEL_DESCRIPTOR_SAMPLER_BUFFER = 0x8DC2,

	MODEL_DESCRIPTOR_UNIFORM_BLOCK = 0x92E2,
	MODEL_DESCRIPTOR_STORAGE_BLOCK = 0x92E6

};
